#!/usr/bin/bash
set -x
cd /data/data/com.termux/files/home/storage/shared/Documents/Me

COMMENT="GusDroid commit $(date)"
COMMIT_LOG="../git-logs/commit-$(date)"
PUSH_LOG="../git-logs/push-$(date)"
git commit -am $COMMENT > $COMMIT_LOG
git push > $PUSH_LOG



